### ISSUE TITLE
remove "extreme flux" message from readme

### ISSUE THREAD

**Issue by elbow-jason** [elbow-jason/bus_car#6]

**Comment by princemaple** [comment]
Lol :) that's a nice looking library!

**Comment by princemaple** [comment]
Maybe change `Repo` to `Index` (or something else) to avoid confusion?

**Comment by elbow-jason** [comment]
@princemaple Hey thanks! My intention was to do a one-to-one mapping with Ecto's `Repo` module to keep the aesthetic of the library close to what elixir devs are used to.

**Comment by elbow-jason** [comment]
@princemaple I had an epiphany. 

Since `BusCar.Repo` is utilized via a `use` macro you can make the "Repo" in an app any name you choose. For example:

```elixir
defmodule PrincemaplesApp.Index do
  use BusCar.Repo, opt_app: :princemaples_app
end
```
Then you would access all the functions available in `Repo` with
```
PrincemaplesApp.Index.<func_name_here>
```

Cheers!

**Comment by princemaple** [comment]
Ah that's a good call.

However, I still want to point out that inheriting the essence from Ecto should be done in the design and the architecture of the library, not in the one-to-one mapping in either module or function names. Using same names for different purposes can cause confusion. And, if this convention is set, it could cause more inconvenience in the scenarios where both an Ecto.Repo and a BusCar.Repo are used, and people normally alias those modules, and there is going to be a conflict in the namespace.

**Comment by elbow-jason** [comment]
The extreme flux message was removed. Closing.
